### ISSUE TITLE
e-column with type="checkbox" and datasource with setted true doesn't work

### ISSUE THREAD

**Issue by LastCodeDE** [syncfusion/ej2-ng-grids#10]
Hello,
we want to set a column in the grid as checkbox. The checkbox has a datasource which is setted true on startup but the grid shows always a not setted checkbox in the column.

[](http://ej2.syncfusion.com/15.4.23/angular/documentation/grid/selection.html)
I can open the documentation about checkbox selection and readjust the issue with plunker on firefox. On chrome it works but only on plunker in my project it doesn't work.

[chrome.zip](https://github.com/syncfusion/ej2-ng-grids/files/1632332/chrome.zip)
[firefox.zip](https://github.com/syncfusion/ej2-ng-grids/files/1632334/firefox.zip)

Regards

**Comment by dhivyasyncfusion** [comment]
Hi @SireCode 

We confirmed that the issue with “Checkbox column binding with datasource is not working” is a defect and we have logged a defect report. The fix for this issue is estimated to be available on January 24, 2018 release. 

Regards, 
R.Dhivya.

**Comment by LastCodeDE** [comment]
Is the fix for the issue available?

**Comment by Pavithra15** [comment]
Hi LastCodeDE,
 
We are glad to announce that patch release(v15.4.26) is rolled out successfully and In that release, we have added the fix for the issue “Checkbox column binding with datasource is not working”. Please update your Essential JavaScript packages to the latest version. 
 
Regards, 
Pavithra S.

**Comment by LastCodeDE** [comment]
Thank you very much for the fix.

Unfortunately the datasource will not automatic updated. When I set a checkbox checked the datasource value will be further false.

There are any ideas?

**Comment by Pavithra15** [comment]
Hi @LastCodeDE ,

We have already fixed the issue 'Checkbox column binding with datasource is not working'. Please update your Essential JavaScript 2 packages to the latest version(v16.1.24). 
Please let us know if you have any queries.

Regards,
Pavithra S.

**Comment by Pavithra15** [comment]
Hi LastCodeDE,

Before validating you query could you please provide the below information that will be helpful for us to provide a better solution.

1.	Do you want to update the dataSource when selecting the record by checkbox?

Regards,
Pavithra S.

**Comment by LastCodeDE** [comment]
Yes exactly.

Now we are using "@syncfusion/ej2-ng-grids": "16.1.24", In this version is the issue "Checkbox column binding with datasource is not working" not fixed anymore. Could you please check this?

**Comment by Pavithra15** [comment]
Hi LastCodeDE,

We have checked your query and the issue ‘Checkbox column binding with datasource is not working’ has been fixed in our Essential JavaScript 2 version 16.2.16. Please upgrade your Essential JavaScript 2 packages to the latest version. you can set the datasource by using the following workaround in which we have updated the data source by using updateCell and batchSave methods of Grid component. Please refer to the following code example sample link and documentation link.

[component.ts]
```
recordClick(e: any) {
if (e.target.classList.contains('e-rowcell')) {
                let args: any = this.grid.getRowInfo(e.target);
                let tr = args.row;
                let val: boolean = !isNullOrUndefined(tr.attributes['aria-selected'])&& tr.attributes['aria-selected'].value ? false : true;
                let rowIndex: number = args.rowIndex;              
              // updates the specified cell by given value without changing into edited state
                 this.grid.editModule.updateCell(rowIndex, 'Active', val);
                //saves the changes in batch editing
                this.grid.editModule.batchSave();
                let btn: any = document.querySelector('#gridEditConfirm').children[1].children[0];
                btn.click();
            }
        }
    }
```
Documentation: 1. https://ej2.syncfusion.com/angular/documentation/grid/api-edit.html#updatecell
                           2. https://ej2.syncfusion.com/angular/documentation/grid/api-edit.html#batchsave

Sample               : https://github.com/Pavithra15/ej2-ng-grids-checkbox 

Regards,
Pavithra S.

**Comment by LastCodeDE** [comment]
Hi Pavithra15,

thank you for the answer. We are using now 16.1.28. 

We don't like this workaround it's to static. Additional it works when I click on the Row but not directly on the checkbox.

Is there a plan when it will be fixed in a version without workaround?

Regards
LastCodeDE

**Comment by Pavithra15** [comment]
Hi LastCodeDE,

Sorry for the inconvenience caused.

We have considered ‘Updating dataSource while selecting the checkbox’ as a feature improvement and logged a report for the same. However, you can update the dataSource while selecting the row by using the following workaround and also we have updated the workaround to support “when I click on the Row but not directly on the checkbox” this scenario.
[component.html]
```
<ejs-grid #grid [dataSource]='data' [toolbar]='toolbar' id='grid' (click)='recordClick($event)' [editSettings]='edit' allowPaging= true >
                  <e-columns>
                  .   .   .
                  </e-columns>
               </ejs-grid>
```
[component.ts]
```export class AppComponent implements OnInit {
         .      .     .
    @ViewChild('grid')
    public grid: GridComponent;
    ngOnInit(): void {
        this.edit = { allowEditing: true, mode: 'Batch', showConfirmDialog: false };
       .     .     .

    }
recordClick(e: any) {
if (e.target.classList.contains('e-rowcell') || e.target.offsetParent.classList.contains('e-rowcell')) {                let args: any = this.grid.getRowInfo(e.target);
                let tr = args.row;
                let val: boolean = !isNullOrUndefined(tr.attributes['aria-selected'])&& tr.attributes['aria-selected'].value ? false : true;
                let rowIndex: number = args.rowIndex;              
              // updates the specified cell by given value without changing into edited state
                 this.grid.editModule.updateCell(rowIndex, 'Active', val);
                //saves the changes in batch editing
                this.grid.editModule.batchSave();
            }
        }
    }

```
Documentation: 1. https://ej2.syncfusion.com/16.1.24/angular/documentation/grid/api-edit.html#updatecell
                              2. https://ej2.syncfusion.com/16.1.24/angular/documentation/grid/api-edit.html#batchsave

Sample               : https://github.com/Pavithra15/ej2-ng-grids-checkbox 

Regards,
Pavithra S.
